version: '3.8'

services:
  php:
    build: ./docker/php
    container_name: yii2-php
    volumes:
      - ./src:/var/www/html
    networks:
      - yii2-network
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: yii2-nginx
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - yii2-network
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: yii2-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql
    networks:
      - yii2-network

volumes:
  mysql_data:

networks:
  yii2-network:
